# Generated by Django 5.0.7 on 2024-07-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDetailModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('logo', models.ImageField(upload_to='site_detail/logo')),
                ('description', models.CharField(max_length=1000)),
                ('non_profile_image', models.ImageField(upload_to='', verbose_name='site_detail/image')),
            ],
        ),
    ]
