# Generated by Django 5.0.7 on 2024-07-25 12:56

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('fullname', models.CharField(max_length=150)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('customuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.customuser')),
                ('ban', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='user/profiles')),
                ('register_date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('last_seen', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('add_group', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('add_channel', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('profile_seen', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('bio', models.CharField(max_length=10000)),
                ('bio_seen', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('story_seen', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('find_with_phone', models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000)),
                ('birth_date', django_jalali.db.models.jDateTimeField(blank=True, null=True)),
                ('report', models.DateTimeField(blank=True, null=True)),
                ('contacts', models.ManyToManyField(related_name='user_contacts', to=settings.AUTH_USER_MODEL)),
                ('favorite_contacts', models.ManyToManyField(related_name='user_favorite_contacts', to=settings.AUTH_USER_MODEL)),
                ('users_allowed_add_channel', models.ManyToManyField(related_name='user_allow_channel_add', to=settings.AUTH_USER_MODEL)),
                ('users_allowed_add_group', models.ManyToManyField(related_name='user_allow_group_add', to=settings.AUTH_USER_MODEL)),
                ('users_allowed_profile_seen', models.ManyToManyField(related_name='user_allow_profile_seen', to=settings.AUTH_USER_MODEL)),
                ('users_allowed_seen', models.ManyToManyField(related_name='user_allow_seen', to=settings.AUTH_USER_MODEL)),
                ('users_allowed_seen_bio', models.ManyToManyField(related_name='user_allow_bio_seen', to=settings.AUTH_USER_MODEL)),
                ('users_allowed_seen_story', models.ManyToManyField(related_name='user_allow_story_seen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.customuser',),
        ),
        migrations.CreateModel(
            name='UserStoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='user/story')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=1000)),
                ('ip', models.CharField(max_length=1000)),
                ('date', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
