# Generated by Django 5.0.7 on 2024-07-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='add_channel',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='add_group',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='find_with_phone',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='story_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
    ]
