# Generated by Django 5.0.7 on 2024-07-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_usermodel_add_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(choices=[('297', '(297) Aruba'), ('93', '(93) Afghanistan'), ('244', '(244) "Angola'), ('1264', '(1264) Anguilla'), ('358', '(358) Aland Islands'), ('355', '(355) Albania'), ('376', '(376) Andorra'), ('971', '(971) United Arab Emirates'), ('54', '(54) Argentina'), ('374', '(374) Armenia'), ('1684', '(1684) American Samoa'), ('1268', '(1268) Antigua and Barbuda'), ('61', '(61) Australia'), ('43', '(43) Austria'), ('994', '(994) Azerbaijan'), ('257', '(257) Burundi'), ('32', '(32) Belgium'), ('229', '(229) Benin'), ('226', '(226) Burkina Faso'), ('880', '(880) Bangladesh'), ('359', '(359) Bulgaria'), ('973', '(973) Bahrain'), ('1242', '(1242) Bahamas'), ('387', '(387) Bosnia and Herzegovina'), ('590', '(590) Saint Barthélemy'), ('375', '(375) Belarus'), ('501', '(501) Belize'), ('1441', '(1441) Bermuda'), ('591', '(591) Bolivia'), ('55', '(55) Brazil'), ('1246', '(1246) Barbados'), ('673', '(673) Brunei'), ('975', '(975) Bhutan'), ('267', '(267) Botswana'), ('236', '(236) Central African Republic'), ('1', '(1) Canada'), ('61', '(61) Cocos (Keeling) Islands'), ('41', '(41) Switzerland'), ('56', '(56) Chile'), ('86', '(86) China'), ('225', '(225) Ivory Coast'), ('237', '(237) Cameroon'), ('243', '(243) DR Congo'), ('242', '(242) Republic of the Congo'), ('682', '(682) Cook Islands'), ('57', '(57) Colombia'), ('269', '(269) Comoros'), ('238', '(238) Cape Verde'), ('506', '(506) Costa Rica'), ('53', '(53) Cuba'), ('5999', '(5999) Curaçao'), ('61', '(61) Christmas Island'), ('1345', '(1345) Cayman Islands'), ('357', '(357) Cyprus'), ('420', '(420) Czech Republic'), ('49', '(49) Germany'), ('253', '(253) Djibouti'), ('1767', '(1767) Dominica'), ('45', '(45) Denmark'), ('1809', '(1809) Dominican Republic'), ('1829', '(1829) Dominican Republic'), ('1849', '(1849) Dominican Republic'), ('213', '(213) Algeria'), ('593', '(593) Ecuador'), ('20', '(20) Egypt'), ('291', '(291) Eritrea'), ('212', '(212) Western Sahara'), ('34', '(34) Spain'), ('372', '(372) Estonia'), ('251', '(251) Ethiopia'), ('358', '(358) Finland'), ('679', '(679) Fiji'), ('500', '(500) Falkland Islands'), ('33', '(33) France'), ('298', '(298) Faroe Islands'), ('691', '(691) Micronesia'), ('241', '(241) Gabon'), ('44', '(44) United Kingdom'), ('995', '(995) Georgia'), ('44', '(44) Guernsey'), ('233', '(233) Ghana'), ('350', '(350) Gibraltar'), ('224', '(224) Guinea'), ('590', '(590) Guadeloupe'), ('220', '(220) Gambia'), ('245', '(245) Guinea-Bissau'), ('240', '(240) Equatorial Guinea'), ('30', '(30) Greece'), ('1473', '(1473) Grenada'), ('299', '(299) Greenland'), ('502', '(502) Guatemala'), ('594', '(594) French Guiana'), ('1671', '(1671) Guam'), ('592', '(592) Guyana'), ('852', '(852) Hong Kong'), ('504', '(504) Honduras'), ('385', '(385) Croatia'), ('509', '(509) Haiti'), ('36', '(36) Hungary'), ('62', '(62) Indonesia'), ('44', '(44) Isle of Man'), ('91', '(91) India'), ('246', '(246) British Indian Ocean Territory'), ('353', '(353) Ireland'), ('98', '(98) Iran'), ('964', '(964) Iraq'), ('354', '(354) Iceland'), ('972', '(972) Israel'), ('39', '(39) Italy'), ('1876', '(1876) Jamaica'), ('44', '(44) Jersey'), ('962', '(962) Jordan'), ('81', '(81) Japan'), ('76', '(76) Kazakhstan'), ('77', '(77) Kazakhstan'), ('254', '(254) Kenya'), ('996', '(996) Kyrgyzstan'), ('855', '(855) Cambodia'), ('686', '(686) Kiribati'), ('1869', '(1869) Saint Kitts and Nevis'), ('82', '(82) South Korea'), ('383', '(383) Kosovo'), ('965', '(965) Kuwait'), ('856', '(856) Laos'), ('961', '(961) Lebanon'), ('231', '(231) Liberia'), ('218', '(218) Libya'), ('1758', '(1758) Saint Lucia'), ('423', '(423) Liechtenstein'), ('94', '(94) Sri Lanka'), ('266', '(266) Lesotho'), ('370', '(370) Lithuania'), ('352', '(352) Luxembourg'), ('371', '(371) Latvia'), ('853', '(853) Macau'), ('590', '(590) Saint Martin'), ('212', '(212) Morocco'), ('377', '(377) Monaco'), ('373', '(373) Moldova'), ('261', '(261) Madagascar'), ('960', '(960) Maldives'), ('52', '(52) Mexico'), ('692', '(692) Marshall Islands'), ('389', '(389) Macedonia'), ('223', '(223) Mali'), ('356', '(356) Malta'), ('95', '(95) Myanmar'), ('382', '(382) Montenegro'), ('976', '(976) Mongolia'), ('1670', '(1670) Northern Mariana Islands'), ('258', '(258) Mozambique'), ('222', '(222) Mauritania'), ('1664', '(1664) Montserrat'), ('596', '(596) Martinique'), ('230', '(230) Mauritius'), ('265', '(265) Malawi'), ('60', '(60) Malaysia'), ('262', '(262) Mayotte'), ('264', '(264) Namibia'), ('687', '(687) New Caledonia'), ('227', '(227) Niger'), ('672', '(672) Norfolk Island'), ('234', '(234) Nigeria'), ('505', '(505) Nicaragua'), ('683', '(683) Niue'), ('31', '(31) Netherlands'), ('47', '(47) Norway'), ('977', '(977) Nepal'), ('674', '(674) Nauru'), ('64', '(64) New Zealand'), ('968', '(968) Oman'), ('92', '(92) Pakistan'), ('507', '(507) Panama'), ('64', '(64) Pitcairn Islands'), ('51', '(51) Peru'), ('63', '(63) Philippines'), ('680', '(680) Palau'), ('675', '(675) Papua New Guinea'), ('48', '(48) Poland'), ('1787', '(1787) Puerto Rico'), ('1939', '(1939) Puerto Rico'), ('850', '(850) North Korea'), ('351', '(351) Portugal'), ('595', '(595) Paraguay'), ('970', '(970) Palestine'), ('689', '(689) French Polynesia'), ('974', '(974) Qatar'), ('262', '(262) Réunion'), ('40', '(40) Romania'), ('7', '(7) Russia'), ('250', '(250) Rwanda'), ('966', '(966) Saudi Arabia'), ('249', '(249) Sudan'), ('221', '(221) Senegal'), ('65', '(65) Singapore'), ('500', '(500) South Georgia'), ('4779', '(4779) Svalbard and Jan Mayen'), ('677', '(677) Solomon Islands'), ('232', '(232) Sierra Leone'), ('503', '(503) El Salvador'), ('378', '(378) San Marino'), ('252', '(252) Somalia'), ('508', '(508) Saint Pierre and Miquelon'), ('381', '(381) Serbia'), ('211', '(211) South Sudan'), ('239', '(239) Sao Tome and Principe'), ('597', '(597) Suriname'), ('421', '(421) Slovakia'), ('386', '(386) Slovenia'), ('46', '(46) Sweden'), ('268', '(268) Swaziland'), ('1721', '(1721) Sint Maarten'), ('248', '(248) Seychelles'), ('963', '(963) Syria'), ('1649', '(1649) Turks and Caicos Islands'), ('235', '(235) Chad'), ('228', '(228) Togo'), ('66', '(66) Thailand'), ('992', '(992) Tajikistan'), ('690', '(690) Tokelau'), ('993', '(993) Turkmenistan'), ('670', '(670) Timor-Leste'), ('676', '(676) Tonga'), ('1868', '(1868) Trinidad and Tobago'), ('216', '(216) Tunisia'), ('90', '(90) Turkey'), ('688', '(688) Tuvalu'), ('886', '(886) Taiwan'), ('255', '(255) Tanzania'), ('256', '(256) Uganda'), ('380', '(380) Ukraine'), ('598', '(598) Uruguay'), ('1', '(1) United States'), ('998', '(998) Uzbekistan'), ('3906698', '(3906698) Vatican City'), ('379', '(379) Vatican City'), ('1784', '(1784) Saint Vincent and the Grenadines'), ('58', '(58) Venezuela'), ('1284', '(1284) British Virgin Islands'), ('1340', '(1340) United States Virgin Islands'), ('84', '(84) Vietnam'), ('678', '(678) Vanuatu'), ('681', '(681) Wallis and Futuna'), ('685', '(685) Samoa'), ('967', '(967) Yemen'), ('27', '(27) South Africa'), ('260', '(260) Zambia'), ('263', '(263) Zimbabwe')], default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='add_channel',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='add_group',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='bio_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='find_with_phone',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='profile_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='story_seen',
            field=models.CharField(choices=[('all', 'All'), ('contacts', 'Contacts'), ('no_one', 'No One')], default='all', max_length=1000),
        ),
    ]
