# Generated by Django 5.1.1 on 2024-10-15 06:09

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCallModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(0, 'Connecting'), (1, 'Not Available'), (2, 'Accepted'), (3, 'Rejected'), (4, 'Busy'), (5, 'Processing'), (6, 'Ended')], default=0, max_length=1000)),
                ('date_started', django_jalali.db.models.jDateTimeField()),
                ('date_ended', django_jalali.db.models.jDateTimeField()),
                ('date_created', django_jalali.db.models.jDateTimeField()),
                ('callee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_callee', to=settings.AUTH_USER_MODEL)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_caller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
