# Generated by Django 5.1.1 on 2024-09-08 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='channeladminmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelchatmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_channel_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelroommodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_channels_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channelroommodel',
            name='users',
            field=models.ManyToManyField(related_name='user_channels', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='channeladminmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_admin', to='chat.channelroommodel'),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='delete_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_room_deleter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_room_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='delete_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='users_delete_chats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user1_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user2_rooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='room_chats', to='chat.chatroommodel'),
        ),
        migrations.AddField(
            model_name='groupadminmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_group_sender', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproommodel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_groups_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouproommodel',
            name='users',
            field=models.ManyToManyField(related_name='user_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupchatmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_chats', to='chat.grouproommodel'),
        ),
        migrations.AddField(
            model_name='groupadminmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_admin', to='chat.grouproommodel'),
        ),
        migrations.AddField(
            model_name='channelchatmodel',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_chats', to='chat.grouproommodel'),
        ),
    ]
