# Generated by Django 5.1.1 on 2024-10-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupchatmodel',
            name='last_message',
        ),
        migrations.AddField(
            model_name='grouproommodel',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
