# Generated by Django 5.1.1 on 2024-10-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_groupchatmodel_last_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='last_message',
        ),
        migrations.AddField(
            model_name='chatroommodel',
            name='last_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
