# Generated by Django 5.1.1 on 2024-10-11 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_remove_chatmodel_last_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='replay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='chat.chatmodel'),
        ),
    ]
